### ISSUE TITLE
springcloud gateway 动态路由配置方式 集成knife4j 使用获取不到SwaggerResourceConfig GatewayProperties中的问题

### ISSUE THREAD

**Issue by SZMOFEI** [xiaoymin/blog-comments#154]
问题背景:
与knife4j官网文档中的springclound gateway 方式集成中不一样的地方是:

- 官方使用的yml中配置route 的方式,即:
```
spring:
  application:
    name: service-gateway
  cloud:
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**
          #            - Header=Cookie,Set-Cookie
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

```
- 我项目中使用的是在数据库中动态加载路由配置 的方式,即:
[Spring Cloud Gateway的动态路由实现](http://www.springcloud.cn/view/407)

会导致下面的问题 :

```
 private final **GatewayProperties** gatewayProperties;
 @Override
    public List<SwaggerResource> get() {
        List<SwaggerResource> resources = new ArrayList<>();
        List<String> routes = new ArrayList<>();
        //获取所有的route ID
        routeLocator.getRoutes().subscribe(route -> routes.add(route.getId()));
        routes.parallelStream().forEach(x -> logger.info(x));
        gatewayProperties.getRoutes().parallelStream().forEach(x -> logger.info(x.getUri().toString()));
        gatewayProperties.getRoutes().stream().map(RouteDefinition::getId).collect(Collectors.toList()).forEach(x-> logger.info(x));
        gatewayProperties.getRoutes().stream().forEach(x->{
            List<PredicateDefinition> predicates = x.getPredicates();
            predicates.forEach(y->logger.info("name: {}",y.getName()));
            predicates.forEach(y->logger.info("args:{}",y.getArgs().toString()));
        });
        gatewayProperties.getRoutes().stream().filter(routeDefinition -> routes.contains(routeDefinition.getId()))
                .forEach(route -> {
                    route.getPredicates().stream()
                            .filter(predicateDefinition -> ("Path").endsWith(predicateDefinition.getName()))
                            .forEach(predicateDefinition -> resources
                                    .add(swaggerResource(route.getId(),
                                            predicateDefinition
                                                    .getArgs()
                                                    .get(NameUtils.GENERATED_NAME_PREFIX + "0")
                                                    .replace("**", "v2/api-docs"))
                                    ));
                });
        return resources;
    }
``` 

**GatewayProperties获取不到route filter 和definition  信息!!!   . 无法正确拼接出正常的swagger resource **

正确的swagger **resource**返回应该是下面这样 
``` 
 name:service-user,location:/user/v2/api-docs
 name:service-order,location:/order/v2/api-docs
```

请问: 1.如果采用动态路由从数据库加载route的话, 此处的如何处理swagger resource  的逻辑,达到拼接正确的返回地址?
